---
controller_credentials:
- name: sat.kona.services
  organization: "{{ my_organization }}"
  credential_type: Red Hat Satellite 6 - that works
  inputs:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    host: "{{ satellite_host }}"

- name: AWS Machine Credential - Ames
  description: ssh key based authentication
  organization: "{{ my_organization }}"
  credential_type: Machine
  inputs:
    username: ec2-user
    ssh_key_data: "{{ ssh_priv_key }}"
    become_method: sudo

- name: AWS Blank Open Environment pvwk8
  organization: "{{ my_organization }}"
  credential_type: Amazon Web Services
  inputs:
    username: "{{ aws_access_key }}"
    password: "{{ aws_secret_key }}"
