---
controller_credential_types:
- name: Red Hat Satellite 6 - that works
  description: The out of the box cred is missing the injectors
  inputs:
    fields:
    - id: host
      type: string
      label: Satellite 6 URL
      help_text: >-
        Enter the URL that corresponds to your Red Hat Satellite 6 server. For
        example, https://satellite.example.org
    - id: username
      type: string
      label: Username
    - id: password
      type: string
      label: Password
      secret: true
  required:
    - host
    - username
    - password
  injectors:
    env:
      SAT_HOST: !unsafe '{{host}}'
      SAT_PASSWORD: !unsafe '{{password}}'
      SAT_USERNAME: !unsafe '{{username}}'

- name: ServiceNow ITSM Credential
  description: ServiceNow ITSM Credential
  inputs:
    fields:
    - id: instance
      type: string
      label: Instance
    - id: username
      type: string
      label: username
    - id: password
      type: string
      label: password
      secret: true
    required:
    - instance
    - username
    - password
  injectors:
    env:
      SN_HOST: !unsafe '{{instance}}'
      SN_PASSWORD: !unsafe '{{password}}'
      SN_USERNAME: !unsafe '{{username}}'
