---
- name: Record the lamp_time
  changed_when: false
  delegate_to: localhost
  register: lamp_time_raw
  ansible.builtin.command:
    cmd: "date '+%H:%M:%S'"

- name: Capture lamp time
  register: lamp_setup_time
  ansible.builtin.set_stats:
    data:
      lamp_setup_time: "{{ lamp_time_raw.stdout }}"

- name: Install the latest version of Firewalld, Apache, Mariadb, php
  ansible.builtin.dnf:
    name:
      - firewalld
      - httpd
      - mariadb-server
      - php
      - php-mysqlnd
    state: present

- name: Starting Firewalld
  ansible.builtin.systemd:
    state: started
    name: firewalld
    enabled: true

- name: Starting httpd
  ansible.builtin.systemd:
    state: started
    name: httpd
    enabled: true

- name: Starting mariadb-server
  ansible.builtin.systemd:
    state: started
    name: mariadb
    enabled: true

- name: Update the firewall for port 443
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Update the firewall for port 80
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Tune the SELinux policy to allow Apache to make network connections to a database
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true
