- name: Server configration management is begining
  hosts: rheldemo
  become: true
  gather_facts: true

  tasks:
    - name: Extract patch report data from stats
      ansible.builtin.set_fact:
        pre_check_services: "{{ patch_reports[inventory_hostname]['pre_check_services'] }}"
        services: "{{ patch_reports[inventory_hostname]['services'] }}"
        pkg_mgr_output: "{{ patch_reports[inventory_hostname]['pkg_mgr_output'] }}"

    - name: Generate patching report
      ansible.builtin.include_role:
        name: zjleblanc.reporting.dnf
      vars:
        linux_patch_run_once: false
        linux_patch_become_publish: true
        linux_patch_output_remote_host: "{{ inventory_hostname }}"
        linux_patch_output_dest: "/var/www/html/patch.html"
